# Generated by Django 5.1 on 2024-08-22 21:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Category',
                'db_table': 'task_manager_category',
                'unique_together': {('name',)},
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique_for_date='created_at', verbose_name='Название')),
                ('description', models.CharField(max_length=255, verbose_name='Описание')),
                ('status', models.CharField(choices=[('New', 'New'), ('In_progress', 'In_progress'), ('Done', 'Done'), ('Pending', 'Pending'), ('Blocked', 'Blocked')], default='New', max_length=50, null=True)),
                ('deadline', models.DateTimeField()),
                ('created_at', models.DateField(auto_now_add=True)),
                ('categories', models.ManyToManyField(to='task_manager_project.category')),
            ],
            options={
                'verbose_name': 'Task',
                'db_table': 'task_manager_task',
                'ordering': ['-created_at'],
                'unique_together': {('title',)},
            },
        ),
        migrations.CreateModel(
            name='SubTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название подзадачи')),
                ('description', models.CharField(max_length=255, verbose_name='Описание')),
                ('status', models.CharField(choices=[('New', 'New'), ('In_progress', 'In_progress'), ('Done', 'Done'), ('Pending', 'Pending'), ('Blocked', 'Blocked')], default='New', max_length=50, null=True)),
                ('deadline', models.DateTimeField()),
                ('created_at', models.DateField(auto_now_add=True)),
                ('task', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='task_manager_project.task')),
            ],
            options={
                'verbose_name': 'Subtask',
                'db_table': 'task_manager_subtask',
                'ordering': ['-created_at'],
                'unique_together': {('title',)},
            },
        ),
    ]
