# Generated by Django 5.1 on 2024-09-03 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager_project', '0003_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('In_progress', 'In_progress'), ('Done', 'Done'), ('Pending', 'Pending'), ('Blocked', 'Blocked')], default='New', max_length=50, null=True),
        ),
    ]
